# This is a basic workflow to help you get started with Actions

name: excercise2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    lab-job:
        runs-on: ubuntu-latest
        steps:
            - name: Start job
              run: echo 'Hello DevOps'
            - name: Second Step
              run: echo 'This is second step'
    second-job:
        runs-on: ubuntu-latest
        needs: lab-job
        steps:
            - name: Start Second job
              run: echo 'Hello Second Job'